[allowlist]
description = "Merged allowlist"
rules = [
  "generic-api-key",
  "aws-access-token"
]
paths = [
  "docs/source/_templates/page.html",
  "notebooks/GE2E-CorentinJ-ExtractSpeakerEmbeddings-by-sample.ipynb",
  "speaker_encoder/notebooks/PlotUmapLibriTTS.ipynb",
  "dataset_analysis/CheckDatasetSNR.ipynb",
  "notebooks/TacotronPlayGround.ipynb"
]
